services:
  fastapi:
    build: ./backend
    container_name: fastapi_application
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      - TZ=Africa/Nairobi
    volumes:
      - ./backend:/app
    restart: always
