services:
  fastapi:
    build: .
    container_name: fastapi_application
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - TZ=Africa/Nairobi
    volumes:
      - .:/app
    restart: always
